# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:38:39+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class ApiV1SuggestGetResponse(BaseModel):
    field_: Optional[List[str]] = None
